sonar.organization=dzana-k
sonar.projectKey=Dzana-K_hello-argo
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
