apiVersion: v1
kind: Service
metadata:
  name: blog-cms-backend
  labels:
    {{- include "blog-cms.labels" . | nindent 4 }}
spec:
  selector:
    app: blog-cms-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 4000
