apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-cms-config
  labels:
    {{- include "blog-cms.labels" . | nindent 4 }}
data:
  DB_HOST: "blog-cms-postgresql"
  DB_PORT: "5432"
  PORT: "4000"
  NODE_ENV: "production"
