apiVersion: v1
kind: Service
metadata:
  name: blog-cms-frontend
  labels:
    {{- include "blog-cms.labels" . | nindent 4 }}
spec:
  selector:
    app: blog-cms-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
