apiVersion: v1
kind: Service
metadata:
  name: blog-cms-postgresql
  labels:
    {{- include "blog-cms.labels" . | nindent 4 }}
spec:
  selector:
    app: blog-cms-postgresql
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
