apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-cms-postgresql
  labels:
    app: blog-cms-postgresql
    {{- include "blog-cms.labels" . | nindent 4 }}
spec:
  serviceName: blog-cms-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: blog-cms-postgresql
  template:
    metadata:
      labels:
        app: blog-cms-postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: blog-cms-db-secret
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.auth.username | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.auth.username | quote }}]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: blog-cms-postgresql-pvc
