apiVersion: v1
kind: Secret
metadata:
  name: blog-cms-db-secret
  labels:
    {{- include "blog-cms.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
