apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-cms-backend
  labels:
    app: blog-cms-backend
    {{- include "blog-cms.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-cms-frontend
  labels:
    app: blog-cms-frontend
    {{- include "blog-cms.labels" . | nindent 4 }}
