backend:
  replicaCount: 1
  image:
    repository: docker.io/dzanak/blog-cms-backend
    tag: "e0a857aaff7239f0e3352cf3bc8b653f079e54b2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
frontend:
  replicaCount: 1
  image:
    repository: docker.io/dzanak/blog-cms-frontend
    tag: "e0a857aaff7239f0e3352cf3bc8b653f079e54b2"
    pullPolicy: Always
  containerPort: 8080
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    readOnlyRootFilesystem: true
postgresql:
  image:
    repository: postgres
    tag: 15-alpine
  storage:
    size: 1Gi
    storageClass: local-path
  auth:
    database: blogdb
    username: bloguser
    password: blogpass
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podSecurityContext:
    fsGroup: 999
  securityContext:
    readOnlyRootFilesystem: true
ingress:
  enabled: true
  className: "nginx"
  host: blog.local
resourceQuota:
  requestsCpu: "2"
  requestsMemory: 2Gi
  limitsCpu: "4"
  limitsMemory: 4Gi
  pods: "10"
  persistentvolumeclaims: "3"
hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70
