backend:
  replicaCount: 1
  image:
    repository: docker.io/dzanak/blog-cms-backend
    tag: "246fd3aa0d555dc2591ae2ff62979b6a660f425a"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
frontend:
  replicaCount: 1
  image:
    repository: docker.io/dzanak/blog-cms-frontend
    tag: "246fd3aa0d555dc2591ae2ff62979b6a660f425a"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    readOnlyRootFilesystem: true
postgresql:
  image:
    repository: postgres
    tag: 15-alpine
  storage:
    size: 1Gi
    storageClass: local-path
  auth:
    database: blogdb
    username: bloguser
    password: blogpass
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    readOnlyRootFilesystem: true
ingress:
  enabled: true
  className: "nginx"
  host: blog.local
resourceQuota:
  requestsCpu: "2"
  requestsMemory: 2Gi
  limitsCpu: "4"
  limitsMemory: 4Gi
  pods: "10"
  persistentvolumeclaims: "3"
hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 70
