apiVersion: v1
kind: ResourceQuota
metadata:
  name: blog-cms-quota
  namespace: blog-cms
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    persistentvolumeclaims: "3"
