apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-cms-backend
  namespace: blog-cms
  labels:
    app: blog-cms-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-cms-frontend
  namespace: blog-cms
  labels:
    app: blog-cms-frontend
