apiVersion: v1
kind: Secret
metadata:
  name: blog-cms-db-secret
  namespace: blog-cms
type: Opaque
stringData:
  DB_USER: bloguser
  DB_PASS: blogpass
  DB_NAME: blogdb
  POSTGRES_USER: bloguser
  POSTGRES_PASSWORD: blogpass
  POSTGRES_DB: blogdb
